name: shiba_akita
channels:
  - pytorch
  - nvidia   
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - notebook
  - transformers
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 
  - fastapi
  - streamlit