_wandb:
    value:
        cli_version: 0.22.0
        code_path: code/src/train.py
        e:
            sgx0w2zyowalmydw9856c3wva8f1s9ax:
                args:
                    - --epochs=100
                    - --learning_rate=5.768636082999064e-05
                    - --patience=5
                codePath: src\train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "998678794240"
                        used: "908335673344"
                email: hso37@gatech.edu
                executable: C:\Users\hozen\anaconda3\envs\shiba_akita\python.exe
                git:
                    commit: 1949990f810c5d16bf67f3043a90058020637b6e
                    remote: https://github.com/terry-so/Fine-Graine-Dog-Breed-Classifier
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-e9715eb1-11d3-4bc7-40cc-f2e8a70d2fbd
                host: DESKTOP-KAVTJ08
                memory:
                    total: "17102364672"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\hozen\Desktop\Projects\Fine-Grained-Dog-Breed-Classifier\src\train.py
                python: CPython 3.11.13
                root: C:\Users\hozen\Desktop\Projects\Fine-Grained-Dog-Breed-Classifier\src
                startedAt: "2025-09-29T17:39:13.216030Z"
                writerId: sgx0w2zyowalmydw9856c3wva8f1s9ax
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 2
                - 14
            "4": 3.11.13
            "5": 0.22.0
            "6": 4.56.2
            "8":
                - 3
            "12": 0.22.0
            "13": windows-amd64
epochs:
    value: 100
learning_rate:
    value: 5.768636082999064e-05
patience:
    value: 5
